############################
## CHANGE THESE
############################

baseURL: 'https://steven5162.github.io/parrott.xyz'
title: 'Steven Parrott'

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
